<a href="https://colab.research.google.com/github/bhargav23/AI/blob/master/UNIT6/Cosine_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn

In [0]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [0]:
text = ['London Paris Paris', 'Paris London London']

In [0]:
cv = CountVectorizer()

In [0]:
count_matrix = cv.fit_transform(text)

In [6]:
for i in count_matrix:
  print(i)

  (0, 0)	1
  (0, 1)	2
  (0, 0)	2
  (0, 1)	1


In [7]:
count_matrix.toarray()

array([[1, 2],
       [2, 1]])

In [8]:
cosine_similarity(count_matrix)

array([[1. , 0.8],
       [0.8, 1. ]])

In [0]:
x = np.random.rand(10)*50
x = x.astype(int)
y = np.random.rand(10)*50
y = y.astype(int)

In [0]:
z = [x,y]

In [11]:
z

[array([40, 15, 39, 25,  1, 14, 39, 28, 28, 47]),
 array([32, 21, 46, 28,  8, 28,  9,  1,  9, 18])]

In [12]:
cosine_similarity(z)

array([[1.        , 0.81219923],
       [0.81219923, 1.        ]])

In [13]:
cosine_similarity([[2, 5], [1, 6]])

array([[1.        , 0.97690002],
       [0.97690002, 1.        ]])

In [0]:
text = ['Some Cats are bats','All bats are Cats']

In [0]:
cv = CountVectorizer()

In [0]:
count_matrix = cv.fit_transform(text)

In [17]:
count_matrix.toarray()

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0]])

In [18]:
cosine_similarity(count_matrix)

array([[1.  , 0.75],
       [0.75, 1.  ]])