<a href="https://colab.research.google.com/github/bhargav23/AI/blob/master/Lab/Different_ways_to_create_NumPy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this lecture
* Numpy
* Creating an array
* Generating arrays using built in functions
* Advantages of Numpy

# Numpy
* Numpy stands for numerical python
* Fundamental package for numerical
computations in Python
* Supports N dimensional array objects
that can be used for processing multi
dimensional data
* Supports different data types



# Using Numpy we can perform
* Mathematical and logical operations on arrays
* Fourier transforms
* Linear algebra operations
* Random number generation

# Arrays
## Create an array
* Ordered collection of elements of basic data types of given
length
* Syntax: numpy.array(object)

In [0]:
import numpy as np

In [0]:
x = np.array([2,3,4,5])

In [3]:
type(x)

numpy.ndarray

In [4]:
print(x)

[2 3 4 5]


### Numpy can handle different categorical entities

In [0]:
x = np.array([2,3,'n',5])

In [7]:
print(x) #All elements are coerced to same data type

['2' '3' 'n' '5']


# Generate arrays
* **numpy.linspace()** - numpy.linspace returns equally spaced numbers within the
given range based on the sample number
* **Syntax:** numpy.linspace(start,stop,num,dtype,retstep)
* **start** start of interval range
* **stop** end of interval range
* **num** number of samples to be generated
* **dtype** type of output array
* **retstep** return the samples, step value

**Generate an array b with start=1 and stop=5**


In [8]:
b=np.linspace(start=1, stop=5, num=10, endpoint=True, retstep =False) 
b

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**Specifying retstep=True returns samples as well the step value** 

In [9]:
c=np.linspace(start=1, stop=5, num=10, endpoint=True,retstep =True)
c

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

* **numpy.arange( )**- returns equally spaced numbers with in the given range based on step size 
* **Syntax:** numpy.arange(start, stop, step) 
* **start** - start of interval range 
* **stop** - end of interval range 
* **step** - step size of interval 

**Generate an array with start=1 and stop=10 by specifying
step=2**

In [10]:
d = np.arange(start = 1, stop = 10, step = 2)
d

array([1, 3, 5, 7, 9])

#Generate arrays using ones( )
* numpy.ones ( )- returns an array of given shape and type filled with ones 
* Syntax: numpy . ones ( shape, dtype) 
* shape - integer or sequence of integers 
* dtype - data type (default float) 

In [11]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#Generate arrays using zeros( )
* nuripy.zeros ( )- returns an array of given shape and type filled with zeros 
* Syntax: numpy . zeros ( shapL, dtype) 
* shape - integer or sequence of integers 
* dtype - data type (default float) 

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#Generate arrays using random.rand ()
* numpy. random. rand( )- returns an array of given shape filled with random values 
* Syntax: numpy. random. rand ( shape) 
* shape - integer or sequence of integers 


In [0]:
x = np.random.rand(5)*1000

In [19]:
x.astype(int)

array([185, 771, 768, 387, 381])

**Generate an array of random values with 5 rows and 2 columns**

In [13]:
np.random.rand(5,2)

array([[0.59690496, 0.33619784],
       [0.09873968, 0.65557995],
       [0.69291961, 0.17374889],
       [0.60152477, 0.56589472],
       [0.84255231, 0.21039797]])

In [0]:
y = np.random.rand(5,2)
y = y*100

In [23]:
y.astype(int)

array([[96, 82],
       [12, 11],
       [30, 74],
       [99, 51],
       [76, 74]])

# Generate arrays using logspace()
* numpy. logspace( )- returns equally spaced numbers based on log scale 
* Syntax: numpy. logspace( start, stop, num, endpoint, base, dtype) 
* start - start value of the sequence 
* stop - end value of the sequence 
* num - number of samples to generate (default : 50) 
* endpoint- if true, stop is the last sample 
* base - base of the log space (default : 10.0) 
* dtype- type of output array 

**Generate an array with 5 samples with base 10.0**


In [24]:
np.logspace(1,10,num =5, endpoint=True,base=10.0)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

# Advantages of numpy
* Numpy supports vectorized operations
* Array operations are carried out in
C and hence the universal functions
in numpy are faster than operations
carried out on python lists

## Advantages of numpy - speed
* **timeit** module can be used to measure the execution time for snippets of code
* Comparing the processing speed of a list and an array using an addition operation

**Creating a list**

In [0]:
x = range(1000)

In [26]:
timeit sum(x)

100000 loops, best of 3: 14.2 µs per loop


**Creating a numpy array**

In [0]:
y = np.arange(1000)

In [28]:
timeit np.sum(y)

The slowest run took 149.80 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.11 µs per loop


## Advantages of numpy - storage space
* Comparing the list x and array y from the previous example to find the memory used at the run time 
* getsizeof()- returns the size of the object in bytes 
* Syntax: sys.getsizeof(object) 
* itemsize- returns the size if one element of a numpy array 
* Syntax: numpy.ndarray.itemsize 

**Size of the list can be found by multiplying the size of an individual element with the number of elements in the list**

In [0]:
import sys

In [30]:
len(x)

1000

In [31]:
sys.getsizeof(1)

28

In [32]:
sys.getsizeof(1)*len(x)

28000

**Size of an array can be found by multiplying the size of an individual element with number of elements in the array**

In [33]:
y.itemsize

8

In [34]:
y.size

1000

In [35]:
y.itemsize * y.size

8000

**Note that numpy array uses less bytes for storage than the
python list.**

#Summary
* Create array
* Generate arrays using functions
  * linspace
  * arange
  * ones
  * zeros
  * random rand
  * logspace
* Advantages of numpy