<a href="https://colab.research.google.com/github/bhargav23/AI/blob/master/Lab/Numpy_Array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this lecture
* Reshape an array
* Numpy operations
* Access elements from an array

## Reshaping an array
reshape() - recasts an array to new shape without changing it’s data

In [0]:
import numpy as np

In [85]:
np.arange(1,10).shape

(9,)

In [0]:
grid = np.arange(1,10).reshape(3,3)

In [87]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array dimensions
* shape() - returns dimensions of an array
* Syntax: array_name.shape()

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

In [89]:
a.shape

(3, 3)

## Numpy addition
* numpy.sum( )- returns sum of all array elements or sum of all array elements over a given axis 
* Syntax: numpy. sum(array, axis) 
In the above syntax, 
  * array() - input array 
  * axis()  - axis along which sum should be calculated 


In [0]:
a = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Calculate overall sum (axis None)**

In [98]:
a.sum(axis=None)

45

In [95]:
np.sum(a,axis=None)

45

**Calculate sum along the column (axis=0)**

In [96]:
np.sum(a,axis=0)

array([12, 15, 18])

**Calculate sum along the row (axis= 1)**

In [97]:
np.sum(a,axis=1)

array([ 6, 15, 24])

### Numpy addition
* numpy.add() - performs elementwise addition between two arrays
* Syntax: numpy.add (array_1,array_2)

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])
b = np.arange(11,20,).reshape(3,3)

In [100]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [102]:
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

# Numpy multiplication
* numpy.multipy() - performs elementwise addition between two arrays
* Syntax: numpy.multipy(array_1,array_2)

In [103]:
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [104]:
np.subtract(a,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [105]:
np.divide(a,b)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [106]:
np.remainder(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Accessing components of an array
* Components of an array can be accessed using index number

**Extract element with index (0, 1 ) from a**

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
a[0,1]

2

**Extract elements from second and third row of array a**

In [114]:
a[1:3] # array[rows ,cols]   array[start:end,start:end] Note: end will be excluded

array([[4, 5, 6],
       [7, 8, 9]])

In [115]:
a[0:2,0:2] #rows 0,1 , col 0,1

array([[1, 2],
       [4, 5]])

**Extract elements from first column of array a**

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
a[:,0:1]

array([[1],
       [4],
       [7]])

**Extract elements the first row of array a**

In [120]:
a[0:1]

array([[1, 2, 3]])

In [122]:
a[0:1,:]

array([[1, 2, 3]])

In [123]:
a[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Subset of arrays
* Subset a 2x2 array from the original array a
* Consider the first two rows and columns from a

In [125]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [0]:
a_sub = a[0:2,0:2]

In [127]:
a_sub

array([[1, 2],
       [4, 5]])

**Here the value 1 should be updated to 1 2**

In [0]:
a_sub[0,0] = 12

In [129]:
a_sub

array([[12,  2],
       [ 4,  5]])

**Modifying the subset will automatically update the original array as well**

In [130]:
print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Modifying array using transpose()
* numpy.transpose() permute the dimensions of array
* Syntax: numpy.transpose (array)

In [131]:
np.transpose(a)

array([[12,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

## Modifying array using append()
* append() - adds values at the end of the array
* Syntax: numpy.append(array,val,axis)
* Adding the new array to a as a row

In [132]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [133]:
np.append(a,[[13,14,15]],axis=0) #axis = 0 means addaing rows

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [13, 14, 15]])

In [0]:
col = [[16],[17],[18]]

In [141]:
col

[[16], [17], [18]]

In [142]:
np.append(a,col,axis=1) #axis = 1 means addaing cols

array([[12,  2,  3, 16],
       [ 4,  5,  6, 17],
       [ 7,  8,  9, 18]])

In [143]:
np.array([19,20,21])

array([19, 20, 21])

In [144]:
np.array([19,20,21]).reshape(3,1)

array([[19],
       [20],
       [21]])

In [0]:
col = np.array([19,20,21]).reshape(3,1)

In [146]:
col

array([[19],
       [20],
       [21]])

In [147]:
np.append(a,col,axis=1) #axis = 1 means addaing cols

array([[12,  2,  3, 19],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 21]])

## Modifying array using insert( )
* insert( ) - adds values at a given position and axis in an
array
* Syntax: numpy.insert(array,obj,values,axis)
  * array: input array
  * obj : index position
  * values : array of values to be inserted
  * axis : axis along which values should be insert

In [148]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

**Insert new array along row and at the 1st index position**

In [0]:
a_ins = np.insert(a,0,[13,14,15],axis=0) #axis = 0 means addaing rows

In [153]:
print(a_ins)

[[13 14 15]
 [12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Modifying array using delete( )
* delete ( )- removes values at a given position and axis in an array 
* Syntax: numpy.delete(array, obj, axis) 
  * array - input array 
  * obj - indicate array to be removed or it's position 
  * axis - axis along which array should be removed 


**Delete third row from the existing array a_ins**

In [154]:
a_ins

array([[13, 14, 15],
       [12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [0]:
a_del = np.delete(a_ins,2,axis=0)

In [159]:
a_del

array([[13, 14, 15],
       [12,  2,  3],
       [ 7,  8,  9]])

In [0]:
a_del = np.delete(a_ins,2,axis=1)

In [161]:
a_del

array([[13, 14],
       [12,  2],
       [ 4,  5],
       [ 7,  8]])

## Summary
  * Reshape an array
  * Numpy operations
  * Accessing components
  * Subset of arrays
  * Modifying array